Adds Support for AWS Provider 4.9+
binbashar/terraform-aws-vpc-flowlogs pull request #11
Opened 2022-04-20 09:47 UTC by lobsterdore

This version works fine with the current S3 setup.

## what
* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
* Use bullet points to be concise and to the point.

## why
* Provide the justifications for the changes (e.g. business case).
* Describe why these changes were made (e.g. why do these commits fix the problem?)
* Use bullet points to be concise and to the point.

## references
* Link to any supporting github issues or helpful documentation to add some context (e.g. stackoverflow).
* Use `closes #123`, if this PR closes a GitHub issue `#123`

2022-04-20 16:25 UTC, diego-ojeda-binbash approved these changes

2022-04-20 16:25 UTC, diego-ojeda-binbash commented on versions.tf
> +    aws = ">= 3.0, != 4.0, != 4.1, != 4.2, != 4.3, != 4.4, != 4.5, != 4.6, != 4.7, != 4.8"
@exequielrafaela does this constraint really need to be so complicated?
How about `>= 3.0`, `< 4.0` and `>= 4.9`?

2022-04-20 16:36 UTC, exequielrafaela commented on versions.tf
> +    aws = ">= 3.0, != 4.0, != 4.1, != 4.2, != 4.3, != 4.4, != 4.5, != 4.6, != 4.7, != 4.8"
@diego-ojeda-binbash I agree on that, @lobsterdore could you please update the constraint with the suggested syntax?

2022-04-21 10:44 UTC, lobsterdore commented on versions.tf
> +    aws = ">= 3.0, != 4.0, != 4.1, != 4.2, != 4.3, != 4.4, != 4.5, != 4.6, != 4.7, != 4.8"
Sure thing, that looks much better.

2022-04-21 12:21 UTC, lobsterdore commented on versions.tf
> +    aws = ">= 3.0, != 4.0, != 4.1, != 4.2, != 4.3, != 4.4, != 4.5, != 4.6, != 4.7, != 4.8"
I gave this a go but I don't think it's possible given the available bits of syntax - https://www.terraform.io/language/expressions/version-constraints

2022-04-21 15:17 UTC, exequielrafaela commented on versions.tf
> +    aws = ">= 3.0, != 4.0, != 4.1, != 4.2, != 4.3, != 4.4, != 4.5, != 4.6, != 4.7, != 4.8"
@lobsterdore I see what you mean, I've tested it and run in the same issue

```
TestAwsVpcFlowLogs 2022-04-21T15:11:43Z logger.go:66: Could not retrieve the list of available versions for provider hashicorp/aws:
TestAwsVpcFlowLogs 2022-04-21T15:11:43Z logger.go:66: locked provider registry.terraform.io/hashicorp/aws 3.75.1 does not match
TestAwsVpcFlowLogs 2022-04-21T15:11:43Z logger.go:66: configured version constraint >= 3.0.0, < 4.0.0, >= 4.9.0; must use terraform
```

So it will be ok to keep the current expression.

2022-04-21 15:30 UTC, exequielrafaela requested changes
@lobsterdore thanks for your collaboration, I've just added some comments regarding Documentation.

One more thing test examples must be updated too please with the new constraint to avoid getting any CI errors => https://github.com/binbashar/terraform-aws-vpc-flowlogs/blob/4ec3c7a3f84b54e17fb9a94bb6c2a789fab35e28/examples/vpc-flowlogs/config.tf#L5

CC: @binbashar/leverage-project-terraform-dev @binbashar/leverage-project-terraform-admin

2022-04-21 15:30 UTC, exequielrafaela commented on README.md
> +| <a name="provider_aws"></a> [aws](#provider\_aws) | => 3.0 |
@lobsterdore this must not be manually edited since it's automatically generated at [CI time by terraform-docs](https://github.com/binbashar/terraform-aws-vpc-flowlogs/blob/4ec3c7a3f84b54e17fb9a94bb6c2a789fab35e28/.circleci/config.yml#L49) 

Flags
- https://github.com/binbashar/terraform-aws-vpc-flowlogs/blob/4ec3c7a3f84b54e17fb9a94bb6c2a789fab35e28/README.md?plain=1#L23
- https://github.com/binbashar/terraform-aws-vpc-flowlogs/blob/4ec3c7a3f84b54e17fb9a94bb6c2a789fab35e28/README.md?plain=1#L65



However since we have a PR from a fork you'll need to locally execute previous to merge w/ the following instructions please:

1. Have re-commit binary installed in your local machine
2. run `pre-commit run --all-files`
   - in case some check fail, run it again since they update the files at the 1st run. 

```
╭─    ~/Binbash/repos/Leverage/terraform/terraform-aws-vpc-flowlogs  on   master +2 ·············································································································· ✔  at 12:23:18 
╰─ pre-commit run --all-files
Check JSON...........................................(no files to check)Skipped
Check for merge conflicts................................................Passed
Check Yaml...............................................................Passed
Detect Private Key.......................................................Passed
Pretty format JSON...................................(no files to check)Skipped
Trim Trailing Whitespace.................................................Passed
Terraform fmt............................................................Passed
Terraform docs...........................................................Passed
```

2022-04-21 15:30 UTC, exequielrafaela commented on README.md
> +
This comment must be added outside the scope of the before commented `terraform-docs` flags please. If not it will automatically removed by our next CI run.

2022-04-22 09:58 UTC, lobsterdore commented
@exequielrafaela I think I've fixed those issues.

2022-04-23 08:10 UTC, lobsterdore commented on .pre-commit-config.yaml
> -  - repo: git://github.com/pre-commit/pre-commit-hooks
I made these changes due to this - https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git

2022-04-23 13:02 UTC, diego-ojeda-binbash approved these changes

2022-04-25 16:13 UTC, merged